sudo: false
language: node_js

notifications:
  email: false

script: npm install -g fog-controller

deploy:
  provider: npm
  email: ${NPM_EMAIL_ADDRESS}
  api_key: ${NPM_AUTH_TOKEN}
  on:
    branch: master
